#! /bin/sh
#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 2001 - 2011, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at http://curl.haxx.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
###########################################################################

prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: curl-config [OPTION]

Available values for OPTION include:

  --built-shared says 'yes' if libcurl was built shared
  --ca        ca bundle install path
  --cc        compiler
  --cflags    pre-processor and compiler flags
  --checkfor [version] check for (lib)curl of the specified version
  --configure the arguments given to configure when building curl
  --features  newline separated list of enabled features
  --help      display this help and exit
  --libs      library linking information
  --prefix    curl install prefix
  --protocols newline separated list of enabled protocols
  --static-libs static libcurl library linking information
  --version   output version information
  --vernum    output the version information as a number (hexadecimal)
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in
    --built-shared)
        echo yes
        ;;

    --ca)
	echo ""/etc/ssl/certs/ca-certificates.crt""
	;;

    --cc)
	echo "arm-brcm-linux-uclibcgnueabi-gcc"
	;;

    --prefix)
	echo "$prefix"
	;;

    --feature|--features)
        for feature in SSL libz NTLM TLS-SRP ""; do
            test -n "$feature" && echo "$feature"
        done
	;;

    --protocols)
        for protocol in DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMTP SMTPS TELNET TFTP; do
            echo "$protocol"
        done
	;;

    --version)
	echo libcurl 7.21.7
	exit 0
	;;

    --checkfor)
        checkfor=$2
        cmajor=`echo $checkfor | cut -d. -f1`
        cminor=`echo $checkfor | cut -d. -f2`
        # when extracting the patch part we strip off everything after a
	# dash as that's used for things like version 1.2.3-CVS
	cpatch=`echo $checkfor | cut -d. -f3 | cut -d- -f1`
        checknum=`echo "$cmajor*256*256 + $cminor*256 + ${cpatch:-0}" | bc`
        numuppercase=`echo 071507 | tr 'a-f' 'A-F'`
        nownum=`echo "obase=10; ibase=16; $numuppercase" | bc`

	if test "$nownum" -ge "$checknum"; then
	  # silent success
	  exit 0
	else
	  echo "requested version $checkfor is newer than existing 7.21.7"
	  exit 1
	fi
	;;

    --vernum)
	echo 071507
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	if test "X${prefix}/include" = "X/usr/include"; then
          echo ""
        else
          echo "-I${prefix}/include"
        fi
       	;;

    --libs)
	if test "X/usr/lib" != "X/usr/lib" -a "X/usr/lib" != "X/usr/lib64"; then
	   CURLLIBDIR="-L/usr/lib "
	else
	   CURLLIBDIR=""
	fi
	if test "Xno" = "Xyes"; then
	  echo ${CURLLIBDIR}-lcurl -ldl -lgcc_s -L/home/plp/k2p/asuswrt/release/src-rt-9.x/src/router/openssl -lssl -lcrypto -lz 
	else
	  echo ${CURLLIBDIR}-lcurl -ldl -lgcc_s -L/home/plp/k2p/asuswrt/release/src-rt-9.x/src/router/openssl 
	fi
	;;

    --static-libs)
	echo /usr/lib/libcurl.a -ldl -lgcc_s -L/home/plp/k2p/asuswrt/release/src-rt-9.x/src/router/openssl -lssl -lcrypto -lz 
	;;

    --configure)
      echo " '--host=arm-linux' '--build=x86_64-linux-gnu' 'CC=arm-brcm-linux-uclibcgnueabi-gcc' '--prefix=/usr' '--bindir=/usr/sbin' '--libdir=/usr/lib' '--enable-http' '--with-ssl=/home/plp/k2p/asuswrt/release/src-rt-9.x/src/router/openssl' 'LDFLAGS=-ldl -lgcc_s' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' 'build_alias=x86_64-linux-gnu' 'host_alias=arm-linux' 'CFLAGS=-DRTAC1200GP -DRTAC1200GP -DBCMWPA2 -DBCMQOS -DEXT_ACS -DD11AC_IOTYPES -DPHYMON -DPROXYARP -DTRAFFIC_MGMT -DTRAFFIC_MGMT_RSSI_POLICY -DMFP -D__CONFIG_MFP__ -DLINUX26 -DCONFIG_BCMWL5 -DDEBUG_NOISY -DDEBUG_RCTEST -pipe -DBCMWPA2 -DBCMARM -fno-strict-aliasing -marm -DRTCONFIG_NVRAM_64K -DLINUX_KERNEL_VERSION=132644  -DRTAC1200GP -O2 -DBCM_DCS -D__CONFIG_EMF__ -D__CONFIG_WPS__'"
    ;;

    *)
        echo "unknown option: $1"
	usage 1
	;;
    esac
    shift
done

exit 0
