static const AVCodec * const codec_list[] = {
    &ff_h263_decoder,
    &ff_h264_decoder,
    &ff_jpegls_decoder,
    &ff_mjpeg_decoder,
    &ff_mpeg1video_decoder,
    &ff_mpeg2video_decoder,
    &ff_mpeg4_decoder,
    &ff_mpegvideo_decoder,
    &ff_aac_decoder,
    &ff_ac3_decoder,
    &ff_atrac3_decoder,
    &ff_mp3_decoder,
    &ff_wmav1_decoder,
    &ff_wmav2_decoder,
    NULL };
